### ISSUE TITLE
Ability to install all available skills

### ISSUE THREAD

**Issue by testman42** [MycroftAI/msm#3]
Would it make sense to have the ability to install all available skills?

Something like `./msm install *` or `./msm install-all` ?

I still don't know if I should be running `msm` with `sudo` or not.

**Comment by Blackbaud-RyanSnedegar** [comment]
Don't use sudo.  
Having once done it, why would anyone want to install all the skills?

**Comment by el-tocino** [comment]
Don't use sudo.  

Having installed all the skills once, why would anyone want to do that?

**Comment by penrods** [comment]
Honestly, I think this is too dangerous -- even today.  I want better interfaces for installing, but "install all the things" is never going to scale.

**Comment by KathyReid** [comment]
There are a number of reasons I can see why this would _not_ be a good idea: 
* multiple Skills of the same type - such as multiple `spotify` or multiple `bitcoin` Skills - people don't need three Skills for the same thing
* installing crap - a lot of our Skills should be retired (we're working on it), but until we can age out Skills, we don't want people installing Skills that are rubbish and will just cause conflicts.
* conflicting `Intents` - the more Skills you have installed, the more chance you have for an `Intent` collision
